# Generated by Django 5.2.4 on 2025-12-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_rename_description_tenant_address_and_more'),
    ]

    operations = [
        # Create TenantSetting model
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date_format', models.CharField(default='Y-m-d', max_length=20)),
                ('time_format', models.CharField(default='H:i:s', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme_color', models.CharField(default='#007bff', max_length=7)),
                ('allow_email_notifications', models.BooleanField(default=True)),
                ('allow_sms_notifications', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='saas.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
        # Update PaymentTransaction model
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='paypal_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='paypal_payer_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_subscription',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.plan'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
