# Generated by Django 5.2.4 on 2025-12-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='Unique domain for tenant URL (auto-generated from company name)', max_length=255, unique=True),
        ),
    ]
