# Generated by Django 6.0 on 2025-12-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_setup_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_email_notifications',
            field=models.BooleanField(default=True, help_text='Allow email notifications'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_sms_notifications',
            field=models.BooleanField(default=False, help_text='Allow SMS notifications'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.plan'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Company Address', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(help_text='Contact Email Address', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(help_text='Contact Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company Logo', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
