# Generated by Django 5.2.3 on 2025-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_paymenttransaction_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='has_limit',
            field=models.BooleanField(default=True, help_text='Whether this feature can have usage limits'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Whether this feature is always unlimited (overrides has_limit)'),
        ),
    ]
