# Generated by Django 6.0 on 2025-12-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_add_feature_limit_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='has_limit',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='is_unlimited',
        ),
    ]
