# Generated by Django 6.0 on 2025-12-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_tenant_slug_alter_paymenttransaction_plan_and_more'),
        ('saas', '0010_remove_feature_limit_fields'),
    ]

    operations = [
    ]
