# Generated by Django 6.0 on 2025-12-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0011_merge_20251216_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add-on name (e.g., Additional Users, Extra Storage)', max_length=255)),
                ('code', models.CharField(help_text="Unique code for the add-on (e.g., 'extra_users', 'extra_storage')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the add-on', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit (e.g., price per user, per GB)', max_digits=10)),
                ('unit_name', models.CharField(default='unit', help_text="Name of the unit (e.g., 'user', 'GB', 'project')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this add-on is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': 'Add-ons',
                'db_table': 'addons',
                'ordering': ['name'],
            },
        ),
    ]
