# Generated by Django 6.0 on 2025-12-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0012_addon_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='allow_email_notifications',
            field=models.BooleanField(default=True, help_text='Allow email notifications'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='allow_sms_notifications',
            field=models.BooleanField(default=False, help_text='Allow SMS notifications'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact Email Address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact Phone Number', max_length=15, null=True),
        ),
    ]
