# Generated by Django 6.0 on 2025-12-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_invoice'),
        ('saas', '0013_alter_permission_tenant_alter_role_tenant_and_more'),
    ]

    operations = [
    ]
