# Generated by Django 6.0 on 2025-12-18 08:01

from django.db import migrations


def fix_tenant_settings_schema(apps, schema_editor):
    """Remove notification columns from tenant_settings if they exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if columns exist and remove them
        try:
            cursor.execute("ALTER TABLE tenant_settings DROP COLUMN allow_email_notifications")
        except:
            pass  # Column might not exist
        try:
            cursor.execute("ALTER TABLE tenant_settings DROP COLUMN allow_sms_notifications")  
        except:
            pass  # Column might not exist


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_merge_20251218_1307'),
    ]

    operations = [
        migrations.RunPython(fix_tenant_settings_schema, migrations.RunPython.noop),
    ]
