# Generated by Django 5.2.4 on 2025-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0016_add_module_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('subscription', 'Subscription'), ('custom', 'Custom')], default='subscription', max_length=20),
        ),
    ]
