# Generated by Django 5.2.4 on 2025-12-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0017_plan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEnterprisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('plan_name', models.CharField(max_length=150)),
                ('employee_limit', models.IntegerField()),
                ('contract_duration', models.IntegerField(help_text='Contract duration in months')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Enterprise Plan',
                'verbose_name_plural': 'Custom Enterprise Plans',
                'db_table': 'custom_enterprise_plans',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OneTimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('license_name', models.CharField(max_length=100)),
                ('one_time_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee_limit', models.IntegerField()),
                ('admin_limit', models.IntegerField()),
                ('support_duration', models.IntegerField(help_text='Support duration in months')),
                ('upgrade_eligible', models.BooleanField(default=True)),
                ('customers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'One Time Plan',
                'verbose_name_plural': 'One Time Plans',
                'db_table': 'one_time_plans',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('billing_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('add_on_category', models.CharField(choices=[('users', 'Users'), ('feature', 'Feature'), ('storage', 'Storage')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Billing Plan',
                'verbose_name_plural': 'Subscription Billing Plans',
                'db_table': 'subscription_billing_plans',
                'ordering': ['-created_date'],
            },
        ),
    ]
