# Generated by Django 5.2.4 on 2025-12-28 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0018_customenterpriseplan_onetimeplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Internal use description', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or flat amount', max_digits=10)),
                ('applicable_model', models.CharField(choices=[('all_products', 'All Products'), ('specific_plan', 'Specific Plan'), ('specific_company', 'Specific Company')], default='all_products', max_length=50)),
                ('scope', models.CharField(choices=[('global', 'Global (Available System-wide)'), ('company_specific', 'Company Specific')], default='global', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_expire', models.BooleanField(default=True)),
                ('allow_stacking', models.BooleanField(default=False, help_text='Can be combined with other discounts')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this discount can be used (null = unlimited)', null=True)),
                ('current_usage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
