# Generated by Django 5.2.4 on 2026-01-05 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0019_add_discount_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flag for companies requiring attention or review'),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Revenue amount in USD', max_digits=15)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)')),
                ('description', models.TextField(blank=True, help_text='Optional revenue description or notes', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'db_table': 'revenue',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='revenue_year_fd8870_idx'), models.Index(fields=['-created_at'], name='revenue_created_5b7a3c_idx')],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
